Ag disease covid
openMetadataInitiative/openMINDS_instances pull request #142
Opened 2024-06-20 09:39 UTC by archgogo

I wish to add two new instances under Disease: coronavirus disease and long COVID

2024-06-20 10:17 UTC, UlrikeS91 requested changes

2024-06-20 10:17 UTC, UlrikeS91 commented on instances/latest/terminologies/disease/coronavirusDisease.jsonld
> +  "definition": "A Coronavirus infectious disease that is characterized by fever, cough and shortness of breath and that has_material_basis_in SARS-CoV-2.",
Rather:
"An infectious disease caused by the severe acute respiratory syndrome coronavirus 2 (SARS-CoV-2), and typically presents with fever, cough and shortness of breath."

2024-06-20 10:17 UTC, UlrikeS91 commented on instances/latest/terminologies/disease/coronavirusDisease.jsonld
> +  "description": "Coronavirus disease 2019 (COVID-19) is an infectious disease caused by severe acute respiratory syndrome coronavirus 2 (SARS-CoV-2)",
remove or extend; right now it does not add any additional information

2024-06-24 10:55 UTC, lzehl requested changes

2024-06-24 10:55 UTC, lzehl commented on instances/latest/terminologies/disease/coronavirusDisease2019.jsonld
>    "preferredOntologyIdentifier": "http://purl.obolibrary.org/obo/DOID_0080600",
Since this is defining all names please and exact synonyms we should stick to them.

2024-06-24 10:55 UTC, lzehl commented on instances/latest/terminologies/disease/coronavirusDisease2019.jsonld
>    "preferredOntologyIdentifier": "http://purl.obolibrary.org/obo/DOID_0080600",
please adapt name, id, and synonyms

2024-06-24 10:55 UTC, lzehl commented on instances/latest/terminologies/disease/coronavirusDisease2019.jsonld
> +  "definition": "An infectious disease caused by the severe acute respiratory syndrome coronavirus 2 (SARS-CoV-2), and typically presents with fever, cough and shortness of breath.",
A coronavirus infectious disease that is characterized by fever, cough and shortness of breath and caused by the coronavirus strain SARS-CoV-2.

2024-07-11 12:53 UTC, UlrikeS91 requested changes
One small typo, otherwise good :)

2024-07-11 12:53 UTC, UlrikeS91 commented on instances/latest/terminologies/disease/COVID-19.jsonld
> +  "@id": "https://openminds.ebrains.eu/instances/disease/coronavirusDisease2019",
change to "COVID-19" (just like you did with the rest)

2024-07-11 13:23 UTC, UlrikeS91 approved these changes

2024-07-11 13:23 UTC, merged