Fix @type and @id of AnalysisTechnique instances
openMetadataInitiative/openMINDS_instances pull request #150
Opened 2024-07-01 14:13 UTC by apdavison

This implements #28. 

It replaces #29, since it also moves instances which were incorrectly moved to `analysisTechnique` back to `technique`.

2024-07-04 09:36 UTC, lzehl requested changes

2024-07-04 09:36 UTC, lzehl commented on instances/latest/terminologies/analysisTechnique/motionCapture.jsonld
not sure if this should remain in AnalysisTechnique. Although some motion capture techniques happen after the measurement (by analyzing the videos) several happen in parallel (and only output the movement tracking results). What do you think?

2024-07-04 09:36 UTC, lzehl commented on instances/latest/terminologies/technique/densityMeasurement.jsonld
I'm not sure if this should not also go into AnalysisTechnique if quantitative and qualitative analysis remains in AnalysisTechnique as well. In many cases density measurements are some kind of quantitative analysis techniques, no? I would either move this back in, or the others out. what do you think?

2024-07-04 09:36 UTC, lzehl commented on instances/latest/terminologies/technique/eyeMovementTracking.jsonld
If this moves out, I would also remove motion capture, no? or leave this in. what do you think?

2024-07-04 09:36 UTC, lzehl commented on instances/latest/terminologies/technique/literatureMining.jsonld
If meta analysis stays in I would also keep literature mining in analysis techniques no? what do you think?

2024-07-04 09:36 UTC, lzehl commented on instances/latest/terminologies/technique/perturbationalComplexityIndexMeasurement.jsonld
this index is calculated and should therefore remain in analysis technique. we may want to rename it to "perturbational complexity index analysis" or "perturbational complexity index processing"

2024-07-04 09:36 UTC, lzehl commented on instances/latest/terminologies/technique/quantification.jsonld
we need to be clear about the difference between quantification and quantitative analysis (otherwise removing this here will be confusing)

2024-07-04 09:36 UTC, lzehl commented on instances/latest/terminologies/technique/reconstructionTechnique.jsonld
isn't this an analysis technique?

2024-07-04 09:36 UTC, lzehl commented on instances/latest/terminologies/technique/singleGeneAnalysis.jsonld
needs a rename if removed out of analysis technique

2024-07-04 09:36 UTC, lzehl commented on instances/latest/terminologies/technique/singleGeneAnalysis.jsonld
suggestion: single gene test

2024-07-04 09:36 UTC, lzehl commented on instances/latest/terminologies/technique/tractTracing.jsonld
I think both: tract tracing and tractography should remain in analysis technique (these are both processing techniques defined by various algorithms). what do you think?

2024-07-04 09:36 UTC, lzehl commented on instances/latest/terminologies/technique/tractography.jsonld
I think both: tract tracing and tractography should remain in analysis technique (these are both processing techniques defined by various algorithms). what do you think?

2024-07-04 10:08 UTC, UlrikeS91 commented on instances/latest/terminologies/analysisTechnique/motionCapture.jsonld
I agree. Theoretically, it belongs in both. If I had to choose one, I would keep it in AnalysisTechnique. Based on the definition, we imply a measurement of movement/position. In most cases, I think this would require some analytics (in parallel to the technique or afterwards), right?  

Definition: 'Motion capture' refers to a group of techniques used to measure the movement and/or position of an object, specimen, or anatomical parts of a specimen over a given period of time.

2024-07-04 10:14 UTC, UlrikeS91 commented on instances/latest/terminologies/technique/literatureMining.jsonld
It's both dependent on how it is performed, I guess. We added it in the context of Ingvilds database, where she read through articles and wrote out certain information into her database by hand. I think it might be ok to keep it as AnalysisTechnique if we do not want to duplicate it (or give the manual approach a different technique name).

2024-07-04 10:16 UTC, UlrikeS91 commented on instances/latest/terminologies/technique/quantification.jsonld
Agreed. The definition for quantification should make it clear that this is only about the "counting" of certain things/properties.

2024-07-04 10:18 UTC, UlrikeS91 commented on instances/latest/terminologies/technique/reconstructionTechnique.jsonld
If "anatomical delineation technique" is an AnalysisTechnique, then "reconstruction technique" should also be one.

2024-07-04 10:21 UTC, UlrikeS91 commented on instances/latest/terminologies/technique/singleGeneAnalysis.jsonld
It could be in both with different names: 
technique: single gene sequencing 
analysis technique: single gene variance test (or keep single gene analysis and adjust definition to exclude the sequencing part and only focus on the "check for genetic changes" part)

2024-07-04 10:28 UTC, UlrikeS91 commented on instances/latest/terminologies/technique/tractTracing.jsonld
I disagree to some degree. The way "tract tracing" has been used so far in EBRAINS, is for the methods around tract tracing (i.e. injection of tract tracer). If we do not want any specific injection techniques, then this could be an analysis technique (with a very clear definition). If we want to have specific injection techniques, we should move it back and change the name to e.g. tract tracer injection. 

Tractography should remain though.

2024-07-04 10:43 UTC, UlrikeS91 requested changes

2024-07-04 10:43 UTC, UlrikeS91 commented on instances/latest/terminologies/technique/DNAMethylationAnalysis.jsonld
Not sure if this should be moved back. Based on these two resources, https://doi.org/10.3390/biology5010003 and https://www.illumina.com/techniques/multiomics/epigenetics/dna-methylation-analysis.html, I would say that the technique to sequence DNA methylations should be a different one than the analysis of DNA methylations. The techniques vary greatly and most of them give you other sequencing information in parallel. The actual analysis techniques probably also vary a lot, but the purpose is at least always the same - analysing DNA methylations.

2024-07-04 10:54 UTC, apdavison commented on instances/latest/terminologies/technique/reconstructionTechnique.jsonld
I'm thinking of neuronal morphology reconstruction, which is typically done directly from a histological specimen under a microscope (e.g. using Neurolucida), so it seems to me much more like data acquisition than analysis of existing data.

Of course, there are also reconstruction techniques that are based on image analysis, so perhaps we need to split this into two instances.

2024-07-04 10:58 UTC, lzehl commented on instances/latest/terminologies/technique/literatureMining.jsonld
manual approaches are also analytical since the person is using (I assume) some criteria to evaluate / extract information

2024-07-04 10:59 UTC, apdavison commented on instances/latest/terminologies/technique/tractTracing.jsonld
I would regard tract tracing as an entire experimental protocol including injection of tracers, specimen preparation, image acquisition... Only the final stage in this is an analysis step.

2024-07-04 11:00 UTC, lzehl commented on instances/latest/terminologies/technique/reconstructionTechnique.jsonld
I would also categorize what is done under neurolucida as analysis / processing technique (just done in parallel with the acquisition).

2024-07-04 11:04 UTC, apdavison commented on instances/latest/terminologies/technique/densityMeasurement.jsonld
Looking at how the term is used in the EBRAINS KG, it seems to refer to a measurement, i.e., the experiment is designed to measure cell or axon-terminal density through using a specific tissue preparation and imaging protocol, followed by an analysis to extract density information from the images. It's not just an analysis technique, therefore, so should be moved back.

2024-07-04 11:11 UTC, apdavison commented on instances/latest/terminologies/technique/reconstructionTechnique.jsonld
I've been following the heuristic that if something involves both data acquisition and analysis, it belongs in the more general `technique`, while `analysisTechnique` should be reserved for "pure" analysis.

2024-07-04 11:11 UTC, lzehl commented on instances/latest/terminologies/technique/perturbationalComplexityIndexMeasurement.jsonld
I understand what you mean but we decided for other cases to separate the acquisition technique from the processing technique even if this processing requires a certain acquisition in place. The reason for this is that the acquisition technique is not reduced to this one processing option but multiple processings can be obtained from it

2024-07-04 11:12 UTC, lzehl commented on instances/latest/terminologies/technique/reconstructionTechnique.jsonld
if we separate, I would suggest to move the current term as suggested and introduce a new term "reconstruction analysis" or "reconstruction processing" for analysis technique

2024-07-16 10:02 UTC, lzehl commented on instances/latest/terminologies/technique/DNAMethylationAnalysis.jsonld
I do not see the analysis separately performed from the experimental assay. I would deal with these methods the same way as we do with imaging techniques (which often also do include some processing/analysis). I suggest (at least for now) to keep this technique in the general Technique terminology

2024-07-16 10:07 UTC, lzehl commented on instances/latest/terminologies/technique/tractTracing.jsonld
if we decide interpreting these "techniques" as protocols than moving them to the general Technique terminology is okay. However I would say that this term interpretation is depending on the community and was introduced for convenient reasons (to avoid details on the actual prior techniques before the track is analyzed). I would prefer interpreting them as processing technique in order to push people to identify as well the techniques prior to the analysis of the track. However, I can live with your suggestion.

2024-07-16 10:11 UTC, lzehl commented on instances/latest/terminologies/technique/singleGeneAnalysis.jsonld
again : I'm not really sure if this is a pure analysis technique. As far as I know nearly all gene analysis is coupled to specific experimental assays. We should keep them all in general Techniques and then discuss those with an expert in the field.

2024-07-16 10:26 UTC, lzehl commented on instances/latest/terminologies/technique/reconstructionTechnique.jsonld
@apdavison I agree with that interpretation: if acquisition and processing/analysis has to be performed in one go to produce some meaningful data, then the technique should be kept in Technique. If a processing/analysis is performed later on the acquisition results or at least does not have to be done in parallel to produce meaningful data the technique should be kept in AnalysisTechnique. In case of Neurolucida I have the feeling that the hardware just combined acquisition and processing for convenience reasons omitting (in one use case) the step of actually storing the image without the annotations. However Neurolucida can also work on prior stored images. So I would interpret the software as an analysis software not an acquisition software (which in those cases would be the microscope that was used to create the image or is showing the enlarged view of the specimen). I would keep reconstruction in AnalysisTechnique

2024-07-16 10:28 UTC, lzehl commented on instances/latest/terminologies/analysisTechnique/motionCapture.jsonld
comparing this with the discussion on reconstruction I would change my opinion here and say we keep motionCapture in AnalysisTechique

2024-07-16 10:30 UTC, lzehl commented on instances/latest/terminologies/technique/densityMeasurement.jsonld
I disagree, because the acquisition performed prior is typically not only used for measuring the density but to give other insight and allow for other processing as well. Density is never directly inferred. There is always an estimation / analysis required.

2024-07-16 10:32 UTC, lzehl commented on instances/latest/terminologies/technique/eyeMovementTracking.jsonld
keep it in AnalysisTechnique based on the discussion around reconstruction and motion capture

2024-07-16 10:34 UTC, lzehl commented on instances/latest/terminologies/technique/tractography.jsonld
see discussion around tract tracing

2024-07-16 10:36 UTC, lzehl commented on instances/latest/terminologies/technique/tractography.jsonld
summary: keep tractography in AnalysisTechnique, move tractTracing to Technique

2024-07-22 13:32 UTC, UlrikeS91 requested changes

2024-07-22 13:32 UTC, UlrikeS91 commented on instances/latest/terminologies/technique/perturbationalComplexityIndexMeasurement.jsonld
keep in techniques; reevaluate later

2024-07-22 13:32 UTC, UlrikeS91 commented on instances/latest/terminologies/technique/reconstructionTechnique.jsonld
difficult to split; keep in analysis technique and re-discuss introducing a new term into techniques when necessary

2024-07-22 13:32 UTC, UlrikeS91 commented on instances/latest/terminologies/technique/singleGeneAnalysis.jsonld
move to techniques; renaming probably necessary, but should be discuss in a separate PR

2024-07-22 13:32 UTC, UlrikeS91 commented on instances/latest/terminologies/technique/tractTracing.jsonld
move tract tracing to techniques but leave tractography in analysis techniques (maybe update definitions to make the split more clear) 

tract tracing = injection of tract tracer (direct measure of the tracts) 
tractography = statistical analysis of imaging data to identify tracts (indirect measure of the tracts)

2024-07-22 13:32 UTC, UlrikeS91 commented on instances/latest/terminologies/technique/tractography.jsonld
see tract tracing comment

2024-07-22 14:52 UTC, apdavison commented
@UlrikeS91 please check the changes in the last commit and merge if all is ok. As agreed, updates to definitions should be done in separate PRs.

2024-07-23 07:55 UTC, UlrikeS91 requested changes

2024-07-23 07:55 UTC, UlrikeS91 commented on instances/latest/terminologies/analysisTechnique/motionAnalysis.jsonld
> +    "motion analysis",
change the name and remove it's new name from the synonym list

2024-07-23 07:55 UTC, UlrikeS91 commented on instances/latest/terminologies/analysisTechnique/eyeMovementAnalysis.jsonld
> +  "definition": "'Eye movement analysis' refers to a group of techniques used to measure eye movements from video or images.",
is "measure" the right word here? Shouldn't it be "...group of techniques used to analyze eye movements..."?

2024-07-23 09:25 UTC, UlrikeS91 approved these changes

2024-07-23 09:25 UTC, merged