Create CA4FieldOfHippocampus.jsonld
openMetadataInitiative/openMINDS_instances pull request #179
Opened 2024-10-25 09:54 UTC by spieschnik

issue #178

2024-10-25 11:37 UTC, UlrikeS91 requested changes
I would like to follow a specific logic for these terms so that we can populate any and all UBERON parcellations programmatically. I have all terms stored locally (which need updating due to the change of our namespace) and https://github.com/openMetadataInitiative/openMINDS_instances/pull/134 is a first PR for those. This is described in https://github.com/openMetadataInitiative/openMINDS_instances/issues/133.

Could you please revise your PR with the content (**but not the namespace!**) of this instance:
```
{
  "@context": {
    "@vocab": "https://openminds.ebrains.eu/vocab/"
  },
  "@id": "https://openminds.ebrains.eu/instances/UBERONParcellation/CA4FieldOfHippocampus",
  "@type": "https://openminds.ebrains.eu/controlledTerms/UBERONParcellation",
  "definition": "Is a hippocampal field. [auto-generated from 'is_a' property of the [UBERON ontology term](http://purl.obolibrary.org/obo/UBERON_0003884)]",
  "description": "The last of four regions in the cornu ammonis of the hippocampus and is also part of the hilus of the dentate gyrus. This area contains mostly mossy cells that receive inputs from the dentate gyrus and pyramidal cells in the CA3 region and also projects back to the dentate gyrus. [definition of the [UBERON ontology term](http://purl.obolibrary.org/obo/UBERON_0003884)]",
  "interlexIdentifier": null,
  "knowledgeSpaceLink": "https://knowledge-space.org/wiki/UBERON:0003884#ca4-field-of-hippocampus",
  "name": "CA4 field of hippocampus",
  "preferredOntologyIdentifier": "http://purl.obolibrary.org/obo/UBERON_0003884",
  "synonym": [
    "CA4",
    "CA4 field",
    "CA4 field of Ammon's horn",
    "CA4 field of cornu ammonis",
    "hippocampus CA4",
    "regio IV cornus ammonis",
    "regio IV hippocampi proprii",
    "region 4 of Ammon's horn",
    "region IV of ammon's horn",
    "region IV of hippocampus proper"
  ]
}
```

2024-11-04 10:37 UTC, UlrikeS91 commented
Sorry for the late response! Content and name space of the updated file are great. Since the auto-population into the version folders isn't running yet, could you also create corresponding files for v4.0 and v3.0 folders? The v4.0 file is identical to the latest file, but v3.0 would actually have the old namespace.

Have a look at this merged PR which also had that: https://github.com/openMetadataInitiative/openMINDS_instances/pull/167.

2024-11-04 12:52 UTC, spieschnik commented
Sure, you can check the new files now

2024-11-04 12:59 UTC, UlrikeS91 approved these changes

2024-11-04 12:59 UTC, merged