Add content types for .bval and .bvec
openMetadataInitiative/openMINDS_instances pull request #18
Opened 2024-02-13 13:29 UTC by eapapp

2024-04-19 08:28 UTC, UlrikeS91 commented
Could somebody with more knowledge about both content types and neuroimaging review this PR? 

@lzehl, maybe @apdavison?

2024-04-19 08:31 UTC, apdavison commented
@Peyman-N can you review this, since it seems to be for MRI data?

2024-04-26 14:36 UTC, lzehl requested changes
I think both content types are defined by the FSL library (https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FDT/UserGuide). Therefore I would suggest the following changes:

"name": "application/vnd.fsl.bval.text"

"name": "application/vnd.fsl.bvec.text"

Maybe add short description for both? Example adapted from the FSL user guide (@Peyman-N and @eapapp feel free to further optimize):

The FSL bval format is used for ASCII text file that contains a list of b-values applied during each volume acquisition. The b-values are assumed to be in s/mm^2 units. The order of entries in this file must match the order of volumes in the diffusion weighted input  data (4D NIFTI file) and entries in the gradient directions text file (FSL bvec format). 

The FSL bvec format is used for ASCII text file that contains a list of gradient directions applied during diffusion weighted volumes. The order of entries in this file must match the order of volumes in the input data (4D NIFTI file).

2024-04-27 16:56 UTC, eapapp commented
Hi Lyuba,

Do we need the ".text" part at the end of the name? Looking at other similar schema names, I was wondering if application/vnd.fsl.bval and application/vnd.fsl.bvec would be enough, since I don't see the ending .text in other names. I'm asking because we need to rename the files as well, I suppose (text_x-bval.jsonld -> application_vnd.fsl.bval.jsonld if I omit the .text part).

What do you think?

All the best,
Eszter

2024-04-29 06:25 UTC, lzehl commented
@eapapp I took this part from IANA as example where often the base format (in this case text) is indicated in the name. @apdavison what do you think? I find these indications useful but I'm not sure I fully understand the IANA naming convention there.

2024-04-29 08:12 UTC, lzehl commented
@apdavison thank you. @eapapp then let's update to "text/vnd.fsl.bval" / "text/vnd.fsl.bvec" (including updating the filenames to "text_vnd.fsl.bval.jsonld" / "text_vnd.fsl.bvec.jsonld")

2024-05-13 07:55 UTC, lzehl commented
@Peyman-N would you please review the changes I made to support the merge of @eapapp PR? If you think this is good please approve and merge

2024-05-13 07:56 UTC, lzehl approved these changes

2024-06-27 15:49 UTC, eapapp commented
Hi @Peyman-N, could you please review and merge this PR if it looks okay? It would be great to have these two content types available in the KG. Thanks a lot! 🙏🏻

2024-07-03 08:51 UTC, Peyman-N commented on instances/latest/contentTypes/text_vnd.fsl.bvec.jsonld
> +  "description": "The FSL bvec format is used for ASCII text file that contains a list of gradient directions applied during diffusion weighted volumes. The order of entries in this file must match t
It is essential for this type to specify that the file contains three rows: the first row for the x-axis, the second row for the y-axis, and the third row for the z-axis.

2024-07-03 08:52 UTC, Peyman-N commented
Hi @eapapp Sorry I don't know why I didn't get any notification for this. 
Just a small modification and I think it is good to go.

2024-07-03 12:31 UTC, eapapp commented
Hi @Peyman-N , I have updated the description. Please let me know if there is anything more I can do (you can also edit the files directly if you like).

2024-07-03 13:03 UTC, Peyman-N approved these changes

2024-07-03 13:05 UTC, merged