Create postnatalDay
openMetadataInitiative/openMINDS_instances pull request #27
Opened 2024-03-22 11:48 UTC by stevevanhooser

Adds postnatal day as a unit of measure

2024-03-22 16:24 UTC, stevevanhooser commented
Hi @lzehl -

There is already a term called embryonic day:

https://github.com/openMetadataInitiative/openMINDS_instances/blob/main/instances/latest/terminologies/unitOfMeasurement/embryonicDay.jsonld

Sounds like a synonym? I am open to the term. Not sure how to express it alongside embryonic day. Although I guess gestationalAge might imply that the organism is being carried by a parent whereas embryonic day is uncertain (could be in a dish or a parent).

2024-03-22 16:28 UTC, lzehl commented
you may be right. I will discuss with the ontology team next week. We can do another PR for this one then if needed.

2024-03-22 17:08 UTC, lzehl requested changes
only a small suggestion

2024-03-22 17:08 UTC, lzehl commented on instances/latest/terminologies/unitOfMeasurement/postnatalDay
> +  "synonym": null
I would add the capital "P" here as synonym and delete the second sentence from the definition.

2024-03-22 18:49 UTC, stevevanhooser commented
Done! Also added the .jsonld file extension.

2024-03-25 11:10 UTC, lzehl approved these changes
made some changes. thanks a lot for this addition :)

2024-03-25 11:11 UTC, merged