Fix @type and @id of AnalysisTechnique instances
openMetadataInitiative/openMINDS_instances pull request #29
Opened 2024-03-25 13:27 UTC by apdavison

This fixes the first part of #28. The question of whether all of these are actually analysis techniques still has to be addressed.

2024-03-26 08:44 UTC, lzehl commented
We need to do the other part first. Otherwise we move instances between types twice. I will comment in the PR which ones I think need to move back to Technique

2024-03-26 09:06 UTC, lzehl requested changes
Here already a first assessment of which instances should probably remain in the Technique terminology

2024-03-26 09:06 UTC, lzehl commented on instances/latest/terminologies/analysisTechnique/reporterProteinBasedExpressionMeasurement.jsonld
not sure about that one

2024-03-26 09:06 UTC, lzehl commented on instances/latest/terminologies/analysisTechnique/singleCellRNASequencing.jsonld
I think this needs to move back to the Technique terminology and remain type Technique

2024-03-26 09:06 UTC, lzehl commented on instances/latest/terminologies/analysisTechnique/singleGeneAnalysis.jsonld
I think this needs to move back to the Technique terminology and remain type Technique

2024-03-26 09:06 UTC, lzehl commented on instances/latest/terminologies/analysisTechnique/singleNucleotidePolymorphismDetection.jsonld
I think this needs to move back to the Technique terminology and remain type Technique

2024-03-26 09:06 UTC, lzehl commented on instances/latest/terminologies/analysisTechnique/video-oculography.jsonld
I wonder about this one (maybe I overlooked others that are similar), because this is a measurement performed by a device no? if yes this would rather stay in Technique

2024-03-26 09:06 UTC, lzehl commented on instances/latest/terminologies/analysisTechnique/wholeGenomeSequencing.jsonld
I think this needs to move back to the Technique terminology and remain type Technique

2024-03-26 10:04 UTC, lzehl commented on instances/latest/terminologies/analysisTechnique/DNAMethylationAnalysis.jsonld
As far as I understand this is a chemical analysis combined with a measurement

2024-03-27 10:07 UTC, lzehl commented on instances/latest/terminologies/analysisTechnique/simulation.jsonld
move back!

2024-03-27 10:07 UTC, lzehl commented on instances/latest/terminologies/analysisTechnique/neuromorphicSimulation.jsonld
move back

2024-03-27 10:07 UTC, lzehl commented on instances/latest/terminologies/analysisTechnique/multi-compartmentModeling.jsonld
move back!

2024-03-27 10:07 UTC, lzehl commented on instances/latest/terminologies/analysisTechnique/morphometricAnalysis.jsonld
https://en.wikipedia.org/wiki/Morphometrics

2024-03-27 10:07 UTC, lzehl commented on instances/latest/terminologies/analysisTechnique/morphometry.jsonld
https://en.wikipedia.org/wiki/Morphometrics

2024-03-27 10:07 UTC, lzehl commented on instances/latest/terminologies/analysisTechnique/morphometricAnalysis.jsonld
keep this with "morphometry" and "morphometrics" as synonym

2024-07-01 11:50 UTC, apdavison commented on instances/latest/terminologies/analysisTechnique/densityMeasurement.jsonld
Looking at how the term is used in the EBRAINS KG, it seems to refer to a measurement, i.e., the experiment is designed to measure cell or axon-terminal density through using a specific tissue preparation and imaging protocol, followed by an analysis to extract density information from the images. It's not just an analysis technique, therefore, so should be moved back.

2024-07-01 11:56 UTC, apdavison commented on instances/latest/terminologies/analysisTechnique/perturbationalComplexityIndexMeasurement.jsonld
I think this is more than an analysis - the technique measures the EEG response to a specific stimulation (TMS), and then performs an analysis.

2024-07-01 12:00 UTC, apdavison commented on instances/latest/terminologies/analysisTechnique/probabilisticDiffusionTractography.jsonld
I think this is an analysis: it's one way in which DTI data can be analysed.

2024-07-01 14:14 UTC, apdavison commented
Replaced by #150

2024-07-01 14:14 UTC, closed without merging