Add LocareJSON ContentType
openMetadataInitiative/openMINDS_instances pull request #75
Opened 2024-05-07 08:50 UTC by UlrikeS91

related to #8

@ingrre and @blixilla, please feel free to review the content as well

2024-10-17 12:44 UTC, lzehl reviewed
updated to new namespace

2025-04-10 13:52 UTC, Raphael-Gazzotti requested changes

2025-04-10 13:54 UTC, Raphael-Gazzotti approved these changes

2025-06-24 08:25 UTC, lzehl requested changes

2025-06-24 08:25 UTC, lzehl commented on instances/latest/contentTypes/application_vnd.locare+json.jsonld
> +  "specification": null,
please also add specification link here

2025-08-20 08:12 UTC, lzehl approved these changes

2025-08-20 08:12 UTC, merged