Create alloy.jsonld
openMetadataInitiative/openMINDS_instances pull request #86
Opened 2024-05-07 11:21 UTC by UlrikeS91

from https://github.com/openMetadataInitiative/openMINDS_controlledTerms/pull/460

Definition is re-written.

2024-10-14 12:50 UTC, Peyman-N approved these changes

2024-10-14 13:05 UTC, lzehl requested changes

2024-10-14 13:07 UTC, UlrikeS91 commented on instances/latest/terminologies/chemicalMixtureType/alloy.jsonld
> +  "definition": "An 'alloy' is a mixture of chemical elements of which at least one is a metal, the atoms are joined by metallic bonding and retains all properties of a metal. [adapted from [wikipedi
done

2024-10-17 15:18 UTC, lzehl approved these changes
updated namespace, populated across versions @Raphael-Gazzotti please double check and merge if okay

2024-10-18 07:42 UTC, Raphael-Gazzotti approved these changes

2024-10-18 07:42 UTC, merged