New cell types - olfactory
openMetadataInitiative/openMINDS_instances pull request #87
Opened 2024-05-07 12:44 UTC by UlrikeS91

from https://github.com/openMetadataInitiative/openMINDS_controlledTerms/pull/459

I tried to incorporate @lzehl feedback as good as possible.

2024-05-07 13:04 UTC, UlrikeS91 commented
Please wait with the review until after I revised this again. I just found https://github.com/openMetadataInitiative/openMINDS_controlledTerms/issues/240 and will add the missing ones for the accessory olf. bulb and revise the existing ones.

2024-05-13 11:13 UTC, UlrikeS91 commented
I've updated the new cell types to be the ones from the main olfactory bulb. Since @apdavison said that there were no use cases for the accessory olfactory bulb, I would like to wait with those until after we did the clean-up for the cell types. @lzehl could you please review the PR?

2024-05-14 12:28 UTC, lzehl commented on instances/latest/terminologies/cellType/mainOlfactoryBulbGranuleNeuron.jsonld
> +  "definition": "'Main olfactory bulb granule neurons' are axonless inhibitory interneurons and form the majority of neurons in the vertebrate main olfactory bulb [adapted from [Egger et al. (2003)](
new convention? "Axonless inhibitory interneurons that form the majority of neurons in the vertebrate main olfactory bulb ..."

2024-05-14 12:34 UTC, lzehl commented on instances/latest/terminologies/cellType/mainOlfactoryBulbGranuleNeuron.jsonld
> +  "definition": "'Main olfactory bulb granule neurons' are axonless inhibitory interneurons and form the majority of neurons in the vertebrate main olfactory bulb [adapted from [Egger et al. (2003)](
OR "A subclass of neurons, axonless and inhibitory, situated in the  the main olfactory bulb of vertebrates."

2024-05-14 12:36 UTC, lzehl commented on instances/latest/terminologies/cellType/mainOlfactoryBulbMitralNeuron.jsonld
> +  "definition": "'Mitral neurons' are a neuronal cell type in the mammalian olfactory bulb, distinguished by the position of their somata located in an orderly row in the mitral cell layer of the bul
adapt to new convention?

2024-05-14 12:36 UTC, lzehl commented on instances/latest/terminologies/cellType/mainOlfactoryBulbPeriglomerularNeuron.jsonld
> +  "definition": "'Periglomerular neurons' are small intrinsic neurons in the glomerular layer of the main olfactory bulb, with cell bodies surrounding the olfactory glomerulus. [adapted from [InterLe
adapt to new convention?

2024-05-14 12:37 UTC, lzehl commented on instances/latest/terminologies/cellType/mainOlfactoryBulbTuftedNeuron.jsonld
> +  "definition": "'Tufted cells' are principle neurons of the mammalian main olfactory bulb.",
adapt to new convention? if not, correct to full name of cell

2024-10-14 13:15 UTC, lzehl requested changes
only remove name from definition (and make clear if it is a superclass)

2024-10-17 15:35 UTC, lzehl approved these changes
updated namespace, updated some definitions, populated across versions @Raphael-Gazzotti could you double check and merge when okay ?

2024-10-17 15:41 UTC, lzehl approved these changes

2024-10-23 06:39 UTC, lzehl commented on instances/v3.0/terminologies/cellType/mainOlfactoryBulbGranuleNeuron.jsonld
> +  "definition": "Axonless inhibitory interneurons and form the majority of neurons in the vertebrate main olfactory bulb [adapted from [Egger et al. (2003)](https://doi.org/10.1523%2FJNEUROSCI.23-20-
Done

2024-10-23 10:03 UTC, merged